# Basic ESPHome RAOP (AirPlay) Media Player Example
# For ESP32-WROVER or ESP32-S3 with PSRAM

substitutions:
  device_name: living-room-speaker
  friendly_name: "Living Room Speaker"

esphome:
  name: ${device_name}
  friendly_name: ${friendly_name}

esp32:
  board: esp32dev  # Or esp32-s3-devkitc-1 for ESP32-S3
  framework:
    type: esp-idf
    version: recommended

# Enable logging
logger:
  level: DEBUG

# Enable Home Assistant API
api:
  encryption:
    key: "GENERATE_YOUR_OWN_KEY"

ota:
  - platform: esphome

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot
  ap:
    ssid: "${device_name} Fallback"
    password: "12345678"

# Required: Enable PSRAM
psram:

# Configure I2S audio bus
i2s_audio:
  id: i2s_bus
  i2s_lrclk_pin: GPIO25  # Word Select / Frame Sync
  i2s_bclk_pin: GPIO26   # Bit Clock

# Add external component
external_components:
  - source: github://jptrsn/esphome-raop
    components: [ raop_media_player ]

# RAOP Media Player
media_player:
  - platform: raop_media_player
    name: "${friendly_name}"
    id: raop_player
    i2s_dout_pin: GPIO22      # Data Out to DAC
    i2s_audio_id: i2s_bus
    buffer_frames: 1024       # Optional: 512-2048, default 1024